### ISSUE TITLE
Doesn't close any tags

### ISSUE THREAD

**Issue by jeramyRR** [mattberkowitz/autoclose-html#30] opened 2014-10-12 22:52 UTC
I can't seem to get this plugin to work at all.  I've tried it on plain html files and html.erb files, and it doesn't close any tags.  I've checked the console for any errors but it's all clean.
I'm using:
 - OS X 10.9.5
 - Atom 0.136.0
 - Autoclose Html 0.12.0

I have Close on End of Opening Tag checked as well as Make Never Close Elements Self Closing.  Everything else is default.

**Comment by ricardograca** [comment] 2015-01-06 12:05
I also confirm that disabling autocomplete-plus makes this package work as intended.

**Comment by jcgallaher** [comment] 2015-01-07 00:36
I can confirm that after disabling autocomplete-plus 1.1.0 that autoclose Html 0.13.0 works. However, I re-enabled autocomplete-plus and the Autoclose HTML plugin still works even after closing Atom and opening it again.

**Comment by vblumen** [comment] 2015-02-03 23:50
I'm still struggling with this issue. I got it to work one time and then I enabled autocomplete plus and it broke again. OSX 10.10.2 , Atom version 0.177.0, autoclose-html 0.14.0. I have now uninstalled autocomplete-plus 2.0.10 and disabled Autocomplete 0.44.0. I've tried enabling and disabling every possible configuration. It doesn't seem to work.

**Comment by vblumen** [comment] 2015-02-05 20:44
I got it to work. How?
1) Complete uninstall of atom using https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084
2) Install Atom
3) Disable Autocomplete that come with it
4) Install autoclos-html
5) click view code>> open autoclose-html.coffee>> mark closeOnEndOfOpeningTag: true
6) Install autocomplete-plus

I hope this helps

**Comment by mattberkowitz** [comment] 2015-02-06 04:16
Odd... `closeOnEndOfOpeningTag` should have no use, I thought I'd removed it, but it's definitely not referenced anywhere other than in configDefaults. Anyway, thanks for mentioning it, I've removed it now.

**Comment by michaelott-stormbox** [comment] 2015-02-23 00:36
I can also confirm, disabling auto-complete-plus makes autoclose-html work, and re-enabling auto-complete-plus afterwards autoclose-html continues to work.

Though one thing I did get caught out with - it only works if the file extension is .html

Trying to edit HTML in any file with a .php extension (Wordpress theme files for example) doesn't seem to work (for me at least), and with that I can't really get much use from this plugin.

That aside, it does work nicely if you're editing a .html file.

**Comment by mikeott** [comment] 2015-02-23 00:38
I can also confirm, disabling auto-complete-plus makes autoclose-html work, and re-enabling auto-complete-plus afterwards autoclose-html continues to work.

Though one thing I did get caught out with - it only works if the file extension is .html

Trying to edit HTML in any file with a .php extension (Wordpress theme files for example) doesn't seem to work (for me at least), and with that I can't really get much use from this plugin.

That aside, it does work nicely if you're editing a .html file.

**Comment by mattberkowitz** [comment] 2015-02-23 02:51
@mikeott You can add "PHP" under the "Additional Grammars" to enable support on files that use the PHP grammar

**Comment by mikeott** [comment] 2015-02-23 10:43
@mattberkowitz cheers - works great now. If I want to include additional grammars there, is it a comma separated list? Or spaces? I'll just assume comma separated because the other fields seem to use that method. But it might be helpful if the field label indicated as such.

**Closed** 2015-06-13 14:48 UTC
