### ISSUE TITLE
multiple lines autoclosing at once creates too many closings 

### ISSUE THREAD

**Issue by miscbits** [mattberkowitz/autoclose-html#102] opened 2015-11-17 18:45 UTC
To replicate this error you need to have multiple lines being edited at once. Open a new tag and when you type in `>` to close the tag it will create and extra closing tag on each opened tag except for the very last one. 

Here is a couple of screenshots when I might try typing in several list items at once. you can see on each list item after I close the tag it generates an extra `</li>` that is not needed

<img width="170" alt="screen shot 2015-11-17 at 1 40 54 pm" src="https://cloud.githubusercontent.com/assets/8864479/11221044/0d2cecde-8d31-11e5-8ff4-d8e0d173eb64.png">
<img width="269" alt="screen shot 2015-11-17 at 1 41 10 pm" src="https://cloud.githubusercontent.com/assets/8864479/11221043/0d2af96a-8d31-11e5-84ef-dede80627125.png">

I also did one with more to show that the number of closes does not scale up with the number of tags opened at once. you just need multiple to be opened at once. 

<img width="308" alt="screen shot 2015-11-17 at 1 44 27 pm" src="https://cloud.githubusercontent.com/assets/8864479/11221112/5c862e30-8d31-11e5-85a2-39373b30eef9.png">

**Comment by miscbits** [comment] 2015-11-17 18:49
Here is what happens when I do this with a block element and not an inline one 
<img width="317" alt="screen shot 2015-11-17 at 1 49 18 pm" src="https://cloud.githubusercontent.com/assets/8864479/11221237/0109f360-8d32-11e5-9892-133ddfb6a979.png">

**Comment by mattberkowitz** [comment] 2016-01-23 23:59
Dupe of #76

**Closed by mattberkowitz** 2016-01-23 23:59 UTC

**Comment by mattberkowitz** [comment] 2016-03-01 22:50
@miscbits With 0.22.0 I changed the method of detecting the end of a tag, which made this a bit better. however you lose the multiple cursors, which isn't perfect.

 I'll refine it a bit more in future releases

**Comment by miscbits** [comment] 2016-03-02 01:53
awesome. I'll take a look at the changes if you dont mind and see if I cant figure something out as well!
