### ISSUE TITLE
Close all tags inline

### ISSUE THREAD

**Issue by yustnip** [mattberkowitz/autoclose-html#51] opened 2015-02-01 00:34 UTC
The package doesn't have an opportunity to set that all tags close inline. Type all tags for that is very boring.

**Comment by raulsntos** [comment] 2015-07-03 12:36
Seems like a duplicate of #3

**Comment by mattberkowitz** [comment] 2016-01-24 00:20
With 0.20.0 you can use "*" for the Force Inline option to accomplish this.

**Closed by mattberkowitz** 2016-01-24 00:20 UTC
Labels: enhancement
